#!/bin/sh

MEMORY_USAGE=$(free -m | awk 'NR==2{printf "%.0f", $3*100/$2}')
COLOR=0

if [ "$MEMORY_USAGE" -ge 90 ]
then
    COLOR=#E06C75
elif [ "$MEMORY_USAGE" -ge 80 ]
then
    COLOR=#E5C07B
fi

echo " ${MEMORY_USAGE}%"
echo " ${MEMORY_USAGE}%"

if [ $COLOR != 0 ]
then
    echo $COLOR
fi