#!/bin/sh

SINK_ID=$(pactl list short sinks | grep -P -o -m1 "^[0-9](?=.*RUNNING)")

VOLUME=$(pactl get-sink-volume ${SINK_ID} | grep -P -o -m1 "[0-9]{1,3}(?=%)" | head -1)
IS_MUTE=$(pactl get-sink-mute ${SINK_ID} | grep -c "yes")

if [ $IS_MUTE ]
then
    if [ $1 -eq 1 ]
    then
        # Unmute
        pactl set-sink-mute $SINK_ID 0
        ICON=󰕾
    else
        ICON=󰖁
    fi
else
    if [ $1 -eq 1 ]
    then 
        # Mute
        pactl set-sink-mute $SINK_ID 1
        ICON=󰖁
    else
        ICON=󰕾
    fi
fi

echo "${ICON} ${VOLUME}%"
echo "${ICON} ${VOLUME}%"
