#!/bin/sh

# Exit if /tmp/monitors-connected file does not exist
if [ ! -f /tmp/monitors-connected ]; then exit; fi

# @USER is set by scripts/dunst.sh
export XAUTHORITY=/home/@USER/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

HDMI_CONNECTED=$(cat /tmp/monitors-connected)
CURRENT_HDMI_CONNECTED=$(xrandr | grep -c "[HDMI|VGA|DP]-[0-9] connected")

if [ $HDMI_CONNECTED -gt $CURRENT_HDMI_CONNECTED ]
then
    # Disconnect
    notify-send -u normal -i "monitor" "Monitor disconnected" "There are ${CURRENT_HDMI_CONNECTED} monitors connected"
else
    # Connect
    notify-send -u normal -i "monitor" "Monitor connected" "There are ${CURRENT_HDMI_CONNECTED} monitors connected"
fi

echo $CURRENT_HDMI_CONNECTED > /tmp/hdmi-connected
