name: Minify Homepage

on:
  push:
    branches:
      - arch-minimal
    paths:
      - homepage/dashboard.html

permissions:
  contents: write

jobs:
  minify-homepage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Minify HTML
        run: |
          npx --yes html-minifier-terser homepage/dashboard.html -o homepage/index.html --collapse-whitespace --remove-comments --remove-attribute-quotes --remove-redundant-attributes --minify-css true --minify-js true
          git add -f homepage/index.html
      - uses: qoomon/actions--create-commit@v1
        id: commit
        with:
          message: "chore(homepage): minify browser homepage"
          skip-empty: true
      - name: Push Changes
        run: git push
