name: Test POSIX compliance

on:
  push:
    paths:
      - '**.sh'
      - 'dunst/scripts/**'
      - 'i3blocks/scripts/**'
      - 'i3lock/**'
      - 'rofi/menus/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs: 
  check: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@main
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: devscripts shellcheck
        version: 1.0

    - name: Run test_posix_compliance.sh
      run: |
        chmod +x ./scripts/test_posix_compliance.sh
        ./scripts/test_posix_compliance.sh
