name: Test POSIX compliance

on:
  push:
    paths:
      - '**.sh'
      - 'dunst/scripts/**'
      - 'i3blocks/scripts/**'
      - 'i3lock/**'
      - 'rofi/menus/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs: 
  check: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@main
    - name: Install dependencies
      run: | 
        sudo apt-get install devscripts
        sudo apt-get install shellcheck

    - name: Run test_posix_compliance.sh
      run: |
        chmod +x ./scripts/test_posix_compliance.sh
        ./scripts/test_posix_compliance.sh
